# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 00be510a734260d95d91c11b89f1e7a906eb1d24cd881ceaaf62cd519730d83f0cadd22bbdd9458888c93150805842f707ab8d3f376f21c3f8e7eab7fe7d093c

test:
  secret_key_base: 8cf81ad02c2437455b07e063a44b0805027371a29e600abda153978b0d53f5758fa6e17e93efb0ae5133add3b7b2e8c59155e6bdbbe25915486e69621775fd77

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
